name: Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Test script execution
      run: |
        sed -i '2 i set -e' onestopsecurity.sh
        chmod +x onestopsecurity.sh
        printf 'y\ny\n22\ny\ny\n127.0.0.1\ny\ny\n12345\nn\ny\ny\n' | ./onestopsecurity.sh
  ubuntu-18:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Test script execution
      run: |
        sed -i '2 i set -e' onestopsecurity.sh
        chmod +x onestopsecurity.sh
        printf 'y\ny\n22\ny\ny\n127.0.0.1\ny\ny\n12345\nn\ny\ny\n' | ./onestopsecurity.sh
  ubuntu-16:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Test script execution
      run: |
        sed -i '2 i set -e' onestopsecurity.sh
        chmod +x onestopsecurity.sh
        printf 'y\ny\n22\ny\ny\n127.0.0.1\ny\ny\n12345\nn\ny\ny\n' | ./onestopsecurity.sh
